# version format
version: 1.0.{build}

# Maximum number of concurrent jobs for the project
max_jobs: 1

# Build worker image (VM template)
image: Visual Studio 2015

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 1

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  project: build/ffmpeg-debug-qp/ffmpeg-debug-qp.sln      # path to Visual Studio solution or project
  # MSBuild verbosity level
  verbosity: normal

artifacts:
  - path: build
